#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"ingress-nginx-controller"}}), expects=1
---
spec:
  type: ClusterIP
